sudo: required

services:
  - docker

language: ruby
rvm: 2.3

before_script:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install nodejs

script:
  - npm install
  - bundle install