plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-assets
  - algoliasearch-jekyll

url: "https://coinium.ch"
baseurl: ""

# Title of website
title: Coinium

#Default keywords (used if no keywords are specified on a page basis)
keywords: Kryptowährung, Kryptowährungen, Bitcoin, Etherum, Litecoin, Cryptocurrency

# Short description of your site
desc: Die schweizer Krypto-Informationsplattform

algolia:
  application_id: '9CSM7E3ECT'
  index_name: 'coinium'
  excluded_files:
    - index.html
    - _layouts/*
    - _includes/*
    - wiki/glossar.html
    - wiki/index.md
    - wiki/waehrungen.html
    - suche.html
  settings:
    attributesToIndex:
      - title
      - h1
      - h2
      - h3
      - p

  read_only_api_key: cbf38e4186918edd9ee123a559e989f8

feed:
  path: atom.xml

avatar: "/img/apple-touch-icon.png"
  
# --- Footer options --- #

# If the values are empty, they are ignored 
profile:
  twitter: CoiniumCH

# To display link in the footer section
pretty-url: "coinium.ch"

# --- Misc --- #

# Your Disqus profile (shortname) settings
disqus: "coinium"

# Set these options as you need (For more information, check Jekyll's site)
timezone: "Europe/Zurich"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /blog/:title
paginate: 5

collections:
  waehrung:
    output: true
    permalink: /:collection/:name
  glossar:
    output: true
    permalink: /:collection/:name

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true
  -
    scope:
      path: "wiki"
    values:
      layout: "wiki_entry"
  -
    scope:
      path: ""
      type: waehrung
    values:
      layout: waehrung
  -
    scope:
      path: ""
      type: glossar
    values:
      layout: "wiki_entry"

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - assets
  - node_modules
  - vendor
  - ci-build.sh
  - Dockerfile
  - gulpfile.js
  - package.json
  - package-lock.json
  - nginx.conf
  - vorlagen

created-by: Coinium
creator-url: https://coinium.ch

assets:
  prefix: "/assets"
  assets:
    - "*.png"
    - "css/styles.css"
    - "js/*.js"
    - "fonts/*"
  sources:
    - "_assets/"